### ISSUE TITLE
psycopg2.ProgrammingError meta.tranquility does not exist

### ISSUE THREAD

**Issue by EveMarketDude** [brentnowak/spotmarket#8]
Encountering the attached error when attempting to view the dashboard after initial start. Looks like the  'meta' table is missing from 0.6 release?
[mozilla.pdf](https://github.com/brentnowak/spotmarket/files/309827/mozilla.pdf)

**Comment by brentnowak** [comment]
I just updated sql/schema.sql and confirmed that the meta schema was lacking. Can you recreate with the new schema and test?

**Comment by EveMarketDude** [comment]
The new schema has resolved this issue.  Thanks for quick reply!

One other problem cropped up that prevented the dashboard from loading:

> AttributeError: 'int' object has no attribute 'strftime' 

for the following two lines in the app/view.py:

```
latestjumpdatatime=latestjumpdatatime().strftime('%Y-%m-%d %H:%M:%S'),
latestsovdatatime=latestsovdatatime().strftime('%Y-%m-%d %H:%M:%S'),
```

I commented them out and verified the dashboard loaded.

**Comment by EveMarketDude** [comment]
Disregard the issue with app/view.py. Working now. It was caused by me trying to get the database populated correctly.

Closing.
